#ifndef CONFIG_H
#define CONFIG_H

#define PEPER_OS_NAME "PeperOS"
#define PEPER_OS_TOTAL_INTERRUPTS 512

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define KERNEL_HEAP_SIZE 104857600 // 100MB
#define KERNEL_HEAP_BLOCK_SIZE 4096 // 4KB

#endif // CONFIG_H